Add -p flag to dsniff

diff --git a/rightscale/dsniff b/rightscale/dsniff
--- a/rightscale/dsniff
+++ b/rightscale/dsniff
@@ -3,11 +3,12 @@
 usage() {
   echo "Docker image sniffer"
   echo
-  echo "Usage: dsniff [-v] [-r] [[org/repo:]tag]"
+  echo "Usage: dsniff [-v] [-r] [-p] [[org/repo:]tag]"
   echo
   echo "Options:"
   echo "  -v  Verbose curl output to stderr"
   echo "  -r  Show remote git branches"
+  echo "  -p  Pull image (slow) and print digest info"
   echo
   echo "Defaults:"
   echo "  If you omit an org/repo:tag specification, we will infer one from PWD"
@@ -32,7 +33,8 @@ depcheck() {
 verbose='-s'
 remote='-l'
 remoteDesc='local'
-while getopts ":vr" opt; do
+
+while getopts ":vrp" opt; do
   case ${opt} in
     v )
       verbose='-v'
@@ -40,6 +42,9 @@ while getopts ":vr" opt; do
     r )
       remote="-r"
       remoteDesc='remote'
+    ;;
+    p )
+      pull=1
     ;;
     \? )
       usage
@@ -102,16 +107,32 @@ fi
 bold=$(tput bold)
 normal=$(tput sgr0)
 
-echo "Image ${org}/${repo}:${tag} built from git.ref ${gitref}"
+echo "Image: ${org}/${repo}:${tag} built from git.ref ${gitref}"
+
+
+if [ -n "$pull" ]; then
+  printf "(pulling Docker image)\r"
+  docker pull ${org}/${repo}:${tag} > /dev/null 2>&1
+  if [ $? == 0 ]; then
+    # Extract "sha256:" plus first 17 chars of digest
+    digest=`docker inspect -f '{{.ID}}' ${org}/${repo}:${tag} | cut -d@ -f2 | cut -c1-24`
+    # Print it so that it aligns with "Image" stuff we printed above
+    echo "Hash:  ${digest}"
+  else
+    echo "Docker pull failed; cannot determine digest"
+  fi
+fi
+
 echo
+
 if [ -d ${GIT_DIR:-.git} ]; then
   if [ $remote == "-r" ]; then
     git fetch
   fi
   echo "The following ${remoteDesc} branches ${bold}POINT AT${normal} ${gitref}:"
-  git branch $remote --points-at $gitref
+  git branch $remote --points-at $gitref 2> /dev/null || echo " (unknown - was image built from `basename $PWD`?)"
   echo
   echo "The following ${remoteDesc} branches ${bold}CONTAIN${normal} ${gitref}:"
-  git branch $remote --contains $gitref
+  git branch $remote --contains $gitref 2> /dev/null || echo " (unknown - was image built from `basename $PWD`?)"
   echo
 fi
